### PR TITLE
Allow Slack bots to create Zendesk tickets

### PR DESCRIPTION
**Pull request by jafacakes2011**
As part of the JML project we have created a slack bot that posts messages to the SRE requests slack channel, however this isn't resulting in the expected tickets being created in Zendesk. This PR aims to fix this.

Summary of the changes:

- Added a new environment variable `ALLOWED_BOT_IDS` which should be a comma separated list of Slack bot IDs
- Updated the message handler to allow bots with an ID that is in the new setting to create tickets in Zendesk

Note: this is currently untested

### CODE REVIEW

**Review by rossmiller — APPROVED** [review]
LGTM!

**Comment by jafacakes2011** [comment]
Tested locally with a custom slack integration and the handler is now configured to correctly listen to bots that are in the allowed bots list

**Review by ejayesh — COMMENTED** [review]
Looks good, could we please deploy this feature to staging zenslackchat to test first before merging.

**Review by ejayesh — APPROVED** [review]
Approved, post succesful testing in staging

**Pull request merged**
